{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: tangods_moenchzmq
  version: {{ data.get('version') }}

source:
  path: ../
build:
  noarch: python
  entry_points:
    - MoenchZmqServer = tangods_moenchzmq:main
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"
  number: 0
requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.10
    - pytango>=9.3.6
    - numpy>=1.24.1
    - pyzmq>=23.2.0
    - numba>=0.57
    - nexpy>=1.0.3

about:
  home: https://github.com/lrlunin/pytango-moenchZmqServer
  license: MIT
  summary: "online processing for PSI moench detector"
  description: processing ZMQ server for a moench detector with tango DeviceServer
  dev_url: https://github.com/lrlunin/pytango-moenchZmqServer
  doc_url: https://lrlunin.github.io/pytango-moenchZmqServer
  doc_source_url: https://github.com/lrlunin/pytango-moenchZmqServer/tree/master/docs
