payload_header = {
    "jsonversion": 4,
    "bitmode": 16,
    "fileIndex": 5,
    "detshape": [1, 1],
    "shape": [400, 400],
    "size": 320000,
    "acqIndex": 1,
    "frameIndex": 1,
    "progress": 100.0,
    "fname": "/mnt/LocalData/DATA/MOENCH/20230128_run/230128",
    "data": 1,
    "completeImage": 1,
    "frameNumber": 1,
    "expLength": 0,
    "packetNumber": 40,
    "bunchId": 0,
    "timestamp": 0,
    "modId": 0,
    "row": 0,
    "column": 0,
    "reserved": 0,
    "debug": 0,
    "roundRNumber": 0,
    "detType": 5,
    "version": 1,
    "flipRows": 0,
    "quad": 0,
    "addJsonHeader": {"detectorMode": "analog", "frameMode": "raw"},
}

dummy_header = {
    "jsonversion": 4,
    "bitmode": 0,
    "fileIndex": 0,
    "detshape": [0, 0],
    "shape": [0, 0],
    "size": 0,
    "acqIndex": 0,
    "frameIndex": 0,
    "progress": 0.0,
    "fname": "",
    "data": 0,
    "completeImage": 0,
    "frameNumber": 0,
    "expLength": 0,
    "packetNumber": 0,
    "bunchId": 0,
    "timestamp": 0,
    "modId": 0,
    "row": 0,
    "column": 0,
    "reserved": 0,
    "debug": 0,
    "roundRNumber": 0,
    "detType": 0,
    "version": 0,
    "flipRows": 0,
    "quad": 0,
}
